title: "ONG Sécurité Vie"
description: "Agir pour sauver des vies au quotidien"
lang: fr
# Adresse du site : www.ongsecuritevie.org
baseurl: ""
collections:
  actualites:
    output: true
    permalink: /actualites/:name/
  activites:
    output: false
  domaines:
    output: true
    permalink: /domaines/:name/
exclude:
  - .pages.yml
defaults:
  - scope:
      path: ""
      type: actualites
    values:
      layout: article
  - scope:
      path: ""
      type: domaines
    values:
      layout: domaine
